var splashes = [
  "you suck at programming",
  "What is the meaning of my Existence...",
  "Certified Dummy.",
  "<p style='color:pink;'>3... 2... 1... GO!!!</p>",
  "<p style='color:pink;'>Get out of my hammer guy!!</p>",
  "<p style='color:pink;'>CONGRATULATIONS</p> <p style='color:red;'>You did it...</p>",
  "what.",
  "Created by GlitchyZorua",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "click those circles",
  "AND HIS NAME IS JOHN CEEEEEENNNAAA",
  "ITS RAINING TACOS",
  "Welcome!",
  "asbestos",
  "Contains no DNI list!"
  "Meow :3",
  "sus",
  "test",
  "Bork",
  "i love hugs :3",
  "Hello!",
  "Hi!",
  "Added ",
  "Firefox > Chrome",
  "if you're feeling useless, just remember that social media exist",
  "<p style='color:pink'>Welcome to Kitty Kart! Beep beep!</p>",
  "Tim Sweeny is in your walls.",
  "The Talking Flower is in your walls.",
  "I don't even have anything to say here",
  "Heyo!",
]
var splashes = splashes[Math.floor(Math.random() * splashes.length)]
